// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fopotquxctaqotrdvfff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcG90cXV4Y3RhcW90cmR2ZmZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTg2NTMsImV4cCI6MjA2NzYzNDY1M30.egTpQcw7AnRVjdJ6RBHsarpwCRREeZLlYkQiwuvz19A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});